spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/redsocial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: 1597
        #url: jdbc:mysql://redsocialdb.cfzlwlklolf9.us-east-1.rds.amazonaws.com:3306/redsocial?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        #username: admin
        #password: adminredsocial2023
    jpa:
        show-sql: false
server:
    port: 4042
    servlet:
        multipart:
        max-file-size: 100MB
        max-request-size: 100MB



